In [1]:
#偶然両方ターゲットになる遺伝子の数を計測

In [2]:
import pandas as pd

In [27]:
YTHDF1_data=pd.read_csv("/Users/miyakesho/Google_Drive/master/research/downloads/GSE63591_C-Y1-Ribosome_profiling.csv")
YTHDF1_data.head(10)

,Gene_symbol,siControl_ribo1,siYTHDF1_ribo1,ribo_log2(siYTHDF1/siControl)1,siControl_RNA1,siYTHDF1_RNA1,polyA_log2(siYTHDF1/siControl)1,TE_log2(siYTHDF1/siControl)1,siControl_ribo2,siYTHDF1_ribo2,ribo_log2(siYTHDF1/siControl),siControl_RNA2,siYTHDF1_RNA2,polyA_log2(siYTHDF1/siControl)2,TE_log2(siYTHDF1/siControl)2,ribo_log2(siYTHDF1/siControl)ave,polyA_log2(siYTHDF1/siControl)ave,TE_log2(siYTHDF1/siControl)ave
0,A4GALT,26.23,17.15,-0.61,3.60,3.39,-0.09,-0.53,3.49,0.87,-2.00,8.36,11.91,0.51,-2.51,-1.31,0.21,-1.52
1,AAAS,160.80,148.75,-0.11,14.76,12.14,-0.28,0.17,41.45,27.44,-0.59,39.22,31.38,-0.32,-0.27,-0.35,-0.30,-0.05
2,AACS,43.31,18.43,-1.23,4.18,3.88,-0.11,-1.12,16.01,8.05,-0.99,9.68,13.93,0.53,-1.52,-1.11,0.21,-1.32
3,AADAT,1.97,3.56,0.86,2.99,2.18,-0.45,1.31,4.48,3.84,-0.22,2.87,3.04,0.08,-0.30,0.32,-0.19,0.50
4,AAED1,57.07,33.83,-0.75,14.53,17.41,0.26,-1.02,47.20,28.77,-0.71,20.16,22.77,0.18,-0.89,-0.73,0.22,-0.95
5,AAGAB,6.59,13.31,1.01,40.07,28.04,-0.51,1.53,18.66,33.61,0.85,34.83,34.94,0.00,0.84,0.93,-0.26,1.19
6,AAK1,0.60,2.74,2.18,3.37,3.93,0.22,1.96,1.31,1.61,0.29,2.62,2.82,0.11,0.18,1.23,0.16,1.07
7,AAMP,36.81,127.20,1.79,13.09,11.63,-0.17,1.96,46.72,22.51,-1.05,40.13,45.91,0.19,-1.25,0.37,0.01,0.36
8,AARS,706.51,315.19,-1.16,117.73,128.06,0.12,-1.29,161.81,88.49,-0.87,131.13,131.65,0.01,-0.88,-1.02,0.06,-1.08
9,AARS2,7.80,11.03,0.50,2.62,3.18,0.28,0.22,2.92,2.23,-0.39,9.06,8.05,-0.17,-0.22,0.06,0.06,0.00

In [30]:
miRNA1_data=pd.read_csv("/Users/miyakesho/Google_Drive/master/research/csv/symboled_miRNA1.csv")
miRNA155_data=pd.read_csv("/Users/miyakesho/Google_Drive/master/research/csv/symboled_miRNA155.csv")
miRNA1_data.head(10)

,Ref_seq,miRNA_rnaseq_log2fc,miRNA_footprint_log2fc,miRNA_TranslEff_log2fc,Gene_symbol
0,NM_017846,-0.295928,-0.378120,-0.082192,TRNAU1AP
1,NM_001516,-0.053095,0.294499,0.347595,GTF2H3
2,NM_001517,0.113749,0.271561,0.157811,GTF2H4
3,NM_004034,0.280818,-0.087530,-0.368349,ANXA7
4,NM_016649,0.872146,1.786011,0.913865,ESF1
5,NM_004749,0.153393,0.442090,0.288697,TBRG4
6,NM_016640,0.644354,0.718117,0.073763,MRPS30
7,NM_016641,-0.071881,0.064189,0.136070,GDE1
8,NM_001862,-0.264713,-0.212363,0.052350,COX5B
9,NM_001863,-0.223459,-0.614738,-0.391279,COX6B1

In [33]:
merge_mir1=pd.merge(YTHDF1_data,miRNA1_data,on="Gene_symbol")
merge_mir155=pd.merge(YTHDF1_data,miRNA155_data,on="Gene_symbol")
merge_mir1.head(10)

,Gene_symbol,siControl_ribo1,siYTHDF1_ribo1,ribo_log2(siYTHDF1/siControl)1,siControl_RNA1,siYTHDF1_RNA1,polyA_log2(siYTHDF1/siControl)1,TE_log2(siYTHDF1/siControl)1,siControl_ribo2,siYTHDF1_ribo2,...,siYTHDF1_RNA2,polyA_log2(siYTHDF1/siControl)2,TE_log2(siYTHDF1/siControl)2,ribo_log2(siYTHDF1/siControl)ave,polyA_log2(siYTHDF1/siControl)ave,TE_log2(siYTHDF1/siControl)ave,Ref_seq,miRNA_rnaseq_log2fc,miRNA_footprint_log2fc,miRNA_TranslEff_log2fc
0,AAMP,36.81,127.20,1.79,13.09,11.63,-0.17,1.96,46.72,22.51,...,45.91,0.19,-1.25,0.37,0.01,0.36,NM_001087,0.004078,0.207701,0.203623
1,AARS2,7.80,11.03,0.50,2.62,3.18,0.28,0.22,2.92,2.23,...,8.05,-0.17,-0.22,0.06,0.06,0.00,NM_020745,0.270779,0.104831,-0.165949
2,AASDHPPT,34.79,60.04,0.79,29.88,40.08,0.42,0.36,83.91,67.69,...,47.11,0.56,-0.87,0.24,0.49,-0.25,NM_015423,0.372796,0.837431,0.464635
3,AATF,66.13,49.56,-0.42,12.95,14.69,0.18,-0.60,110.76,15.55,...,19.62,-0.36,-2.47,-1.62,-0.09,-1.53,NM_012138,0.253192,0.267174,0.013982
4,ABCA7,4.59,6.06,0.40,2.96,3.42,0.21,0.19,1.60,0.78,...,6.79,0.12,-1.16,-0.32,0.17,-0.48,NM_019112,-0.872929,-1.008692,-0.135763
5,ABCB6,61.78,88.19,0.51,14.09,15.32,0.12,0.39,24.86,12.44,...,27.87,0.29,-1.29,-0.24,0.21,-0.45,NM_005689,-1.077833,-0.989989,0.087844
6,ABCB7,66.89,100.77,0.59,25.90,33.04,0.35,0.24,38.62,38.62,...,25.30,0.03,-0.03,0.30,0.19,0.10,NM_004299,-0.721070,-0.460770,0.260300
7,ABCC1,29.32,32.11,0.13,3.84,3.89,0.02,0.11,14.86,10.94,...,10.29,0.58,-1.02,-0.16,0.30,-0.45,NM_004996,-0.126532,-0.356293,-0.229761
8,ABCC4,27.17,33.44,0.30,20.33,18.89,-0.11,0.41,32.75,26.10,...,22.72,0.36,-0.69,-0.01,0.13,-0.14,NM_005845,-0.287321,-0.723842,-0.436522
9,ABCC5,9.76,18.78,0.94,6.60,7.30,0.15,0.80,193.10,417.91,...,8.26,0.29,0.83,1.03,0.22,0.81,NM_005688,-0.087511,0.066987,0.154499

In [34]:
gene_length1=len(merge_mir1)
gene_length155=len(merge_mir155)
print(gene_length1,gene_length155)

2909 3511

In [12]:
miR1target=266+512
YTHDFtarget=1102+512

In [35]:
miR1_prob=miR1target/gene_length1
YTHDF1_prob=YTHDFtarget/gene_length1
miR1_chance=miR1_prob*YTHDF1_prob
print(miR1_prob,YTHDF1_prob,miR1_chance)

0.26744585768305257 0.554829838432451 0.14838694200771635

In [36]:
miR1_chance*gene_length1

431.6576143004469

In [21]:
miR155_target=400+249
YTHDF1_target=400+1634

In [37]:
miR155_prob=miR155_target/gene_length155
YTHDF1_prob=YTHDF1_target/gene_length155
miR155_chance=miR155_prob*YTHDF1_prob
print(miR155_prob,YTHDF1_prob,miR155_chance)

0.1848476217601823 0.5793221304471661 0.10708631804620074

In [38]:
miR155_chance*gene_length155

375.98006266021076